android_library(
  name = "DemoActivity",
  srcs = ["DemoActivity.java"],
  manifest = "AndroidManifest.xml",
  exports_manifest = 1,
  resource_files = glob(["res/**"]),
  visibility = ["//visibility:public"],
)
